# Site settings
title: My Personal Wiki 
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/mywiki/" # the subpath of your site, e.g. /blog/
url: "http://ling.cf" # the base hostname & protocol for your site
twitter_username: username
github_username: villanella 

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
